#
query AboutPageQuery($sysID: String!) {
	aboutPage(id: $sysID) {
		slug
		title
		name
		bannerImage {
			width
			height
			url
			description
		}
		buildingBlocksCollection {
			items {
				__typename
				... on TextBlock {
					sys {
						id
					}
					title
					description {
						json
					}
				}
				... on PortfolioCards {
					detailPagesCollection {
						items {
							sys {
								id
							}
							slug
							title
							imageCollection(limit: 1) {
								items {
									url
									title
								}
							}
						}
					}
				}
			}
		}
	}
}
