#
query CollectionPageBySlug($slug: String!) {
	collectionPageCollection(where: { slug: $slug }, limit: 1) {
		items {
			slug
			title
			subtitle
			description {
				json
			}
			sortingEnabled
			contentfulMetadata {
				tags {
					id
					name
				}
			}
		}
	}
}
