#
query ContactPage($seoMetaDataSysID: String!, $contactPageSysID: String!, $artistSysID: String!, $addressSysID: String!) {
	seoMetaData(id: $seoMetaDataSysID) {
		title
		description
		keywords
	}
	contactPage(id: $contactPageSysID) {
		slug
		name
		title
		description {
			json
		}
		formIntro
		submitButtonText
	}
	artist(id: $artistSysID) {
		name
		occupation
		description
		telephone
		email
		mentions
	}
	address(id: $addressSysID) {
		streetAddress
		zipCode
		city
		country
	}
}
