#
query DetailPagesByTagIDs($tagIDs: [String]!, $order: [DetailPageOrder]!, $limit: Int, $skipId: String) {
	detailPageCollection(
		where: { contentfulMetadata: { tags: { id_contains_all: $tagIDs } }, sys: { id_not: $skipId } }
		order: $order
		limit: $limit
	) {
		total
		items {
			sys {
				id
			}
			slug
			title
			imageCollection(limit: 1) {
				items {
					url
					title
					description
				}
			}
		}
	}
}
