query DetailPageBySlug($slug: String!) {
	detailPageCollection(where: { slug: $slug }, limit: 1) {
		items {
			slug
			name
			title
			description
			status
			creationDate
			imageCollection(limit: 1) {
				items {
					url
					title
				}
			}
		}
	}
}
