#
query DetailPagesByTagIDs($tagIDs: [String]!) {
	detailPageCollection(where: { contentfulMetadata: { tags: { id_contains_all: $tagIDs } } }) {
		items {
			sys {
				id
			}
			slug
			title
			imageCollection(limit: 1) {
				items {
					url
					title
					description
				}
			}
		}
	}
}
