query DetailPageBySlug($slug: String!) {
	detailPageCollection(where: { slug: $slug }, limit: 1) {
		items {
			slug
			name
			title
			description {
				json
			}
			status
			creationDate
			imageCollection(limit: 1) {
				items {
					sys {
						id
					}
					url
					title
					description
				}
			}
			imageCarousel {
				description {
					json
				}
				showDescription
				imageCollection {
					items {
						sys {
							id
						}
						url
						title
						description
					}
				}
			}
		}
	}
}
