query DetailPageBySlug($slug: String!, $artistSysID: String!, $addressSysID: String!) {
	detailPageCollection(where: { slug: $slug }, limit: 1) {
		items {
			sys {
				id
			}
			seoMetaData {
				title
				description
				keywords
			}
			slug
			title
			description {
				json
			}
			material
			dimensions
			price
			status
			creationDate
			imageCollection(limit: 1) {
				items {
					sys {
						id
					}
					url
					title
					description
				}
			}
			mainImageAuthor {
				name
				url
			}
			imageCarousel {
				description {
					json
				}
				showDescription
				imageCollection {
					items {
						sys {
							id
						}
						url
						title
						description
						width
						height
					}
				}
			}
			relatedItemsTags
			contentfulMetadata {
				tags {
					id
					name
				}
			}
		}
	}
	artist(id: $artistSysID) {
		name
		occupation
		description
		telephone
		email
		mentions
	}
	address(id: $addressSysID) {
		streetAddress
		zipCode
		city
		country
	}
}
