#
query HomePageData($sysID: String!) {
	homePage(id: $sysID) {
		seoMetaData {
			title
			description
			keywords
		}
		slug
		title
		subtitle
		mugshot {
			url
			description
			width
			height
		}
		description {
			json
		}
		buildingBlocksCollection {
			items {
				__typename
				... on PortfolioCards {
					detailPagesCollection {
						items {
							sys {
								id
							}
							slug
							title
							imageCollection(limit: 1) {
								items {
									url
									title
								}
							}
						}
					}
				}
			}
		}
	}
}
