#

query HomePageData($homePageSysID: String!, $artistSysID: String!, $addressSysID: String!) {
	homePage(id: $homePageSysID) {
		slug
		title
		subtitle
		mugshot {
			url
			description
			width
			height
		}
		description {
			json
		}
		buildingBlocksCollection {
			items {
				__typename
				... on PortfolioCards {
					detailPagesCollection {
						items {
							sys {
								id
							}
							slug
							title
							imageCollection(limit: 1) {
								items {
									url
									title
								}
							}
						}
					}
				}
			}
		}
	}
	artist(id: $artistSysID) {
		name
		occupation
		description
		telephone
		email
		mentions
	}
	address(id: $addressSysID) {
		streetAddress
		zipCode
		city
		country
	}
}
