#
query Navigation($sysID: String!) {
	navigation(id: $sysID) {
		title
		description
		navigationItemsCollection {
			items {
				... on NavigationPageEntry {
					name
					page {
						... on HomePage {
							sys {
								id
							}
							slug
						}
						... on AboutPage {
							sys {
								id
							}
							slug
						}
						... on CollectionPage {
							sys {
								id
							}
							slug
						}
						... on ContactPage {
							sys {
								id
							}
							slug
						}
					}
					subNavigation {
						sys {
							id
						}
					}
				}
			}
		}
	}
}
