name: TEST

on:
    push:
        branches-ignore:
            - main

concurrency:
    group: main-workflow
    cancel-in-progress: true

jobs:
    eslint:
        name: Run ESLint
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node 20.17.0
              uses: actions/setup-node@v4
              with:
                  node-version: 20.17.0

            - name: Install Dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

    cypress-run:
        name: Run Cypress E2E Tests
        needs: eslint
        runs-on: ubuntu-22.04
        strategy:
            # when one test fails, DO NOT cancel the other
            # containers, because this will kill Cypress processes
            # leaving Cypress Cloud hanging ...
            # https://github.com/cypress-io/github-action/issues/48
            fail-fast: false
            matrix:
                # run 3 copies of the current job in parallel
                containers: [1, 2, 3]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                  record: true
                  parallel: true
                  group: 'Cypress Tests'
                  browser: chrome
                  build: npm run build
                  start: npm start
                  wait-on: 'http://localhost:3000'
              env:
                  NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}
                  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  NEXT_PUBLIC_EMAILJS_USER_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_USER_ID }}
                  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
                  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}}
                  RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY}}
