name: Validate Commit and Run Tests

on:
    push:
        branches-ignore:
            - main

jobs:
    validate-commit-message:
        name: Validate Commit
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.1.0

    cypress-run:
        runs-on: ubuntu-22.04
        name: Run e2e Tests
        needs: validate-commit-message
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  project: ./cypress
                  browser: chrome
                  build: yarn build
                  start: yarn start
                  wait-on: 'http://localhost:4000'

    # test:
    #     runs-on: ubuntu-22.04
    #     needs: validate-commit-message
    #     steps:
    #         - name: Checkout Repository
    #           uses: actions/checkout@v2

    #         - name: Set Up Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: 18.17.0

    #         - name: Install Dependencies
    #           run: npm ci

    #         - name: Run Jest Tests
    #           run: npm test
