name: Validate Commit and Run Tests

on:
    push:
        branches-ignore:
            - main

jobs:
    validate-commit-message:
        name: Validate Commit
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.1.0

    cypress-run:
        runs-on: ubuntu-22.04
        name: Run Cypress Tests
        needs: validate-commit-message
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  #   record: true
                  parallel: true
                  group: 'Cypress Tests'
                  browser: chrome
                  build: npm run build
                  start: npm start
                  wait-on: 'http://localhost:3000'
              env:
                  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  RESEND_EMAIL: ${{ secrets.RESEND_EMAIL }}

    # test:
    #     runs-on: ubuntu-22.04
    #     needs: validate-commit-message
    #     steps:
    #         - name: Checkout Repository
    #           uses: actions/checkout@v2

    #         - name: Set Up Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: 18.17.0

    #         - name: Install Dependencies
    #           run: npm ci

    #         - name: Run Jest Tests
    #           run: npm test
