name: Validate Commit and Run Tests

on:
    push:
        branches-ignore:
            - main

env:
    CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
    CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    RESEND_EMAIL: ${{ secrets.RESEND_EMAIL }}
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}

jobs:
    validate-commit-message:
        name: Validate Commit Message
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.3.0

    eslint:
        name: Run ESLint
        runs-on: ubuntu-22.04
        needs: validate-commit-message
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node 18.17.0
              uses: actions/setup-node@v4
              with:
                  node-version: 18.17.0
            - name: Install Dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint

    unit-tests:
        name: Run Jest Unit- and Snapshot Tests
        runs-on: ubuntu-22.04
        needs: eslint
        strategy:
            matrix:
                shard: [1, 2, 3, 4]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.17.0
            - name: Install Dependencies
              run: npm ci
            - name: Run Jest Tests
              run: npm test --shard=${{ matrix.shard }}/${{ strategy.job-total }} --coverage

    e2e-tests:
        name: Run Cypress e2e Tests
        runs-on: ubuntu-22.04
        needs: eslint
        strategy:
            # when one test fails, DO NOT cancel the other
            # containers, because this will kill Cypress processes
            # leaving Cypress Cloud hanging ...
            # https://github.com/cypress-io/github-action/issues/48
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                  record: true
                  parallel: true
                  group: 'Cypress Tests'
                  browser: chrome
                  build: npm run build
                  start: npm start
                  wait-on: 'http://localhost:3000'
